env:
  global:
    - secure: jNWCPpEX4xaZgLH5O7j1yhGozU/rzmf9YrT7brdCcqbYKKTjNt7997dunJNaN00NIwQx9WXWfgljScom3huiCr0Uix9ltjueAP2j/gU9MWgZWRvhBnSJIGcgQah6tmKQgvlX2JkpIfbLDlq336fhMUyUC96rA1SHcievc/mNwPM=

language: rust

after_script:
  - cargo doc
  - cp -R target/doc doc
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
